language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruit_basket

before_script:
  - psql -c 'create database fruit_basket;' -U postgres
  - psql -U postgres -d Fruit_Basket -a -f table.sql

services:
  - postgresql