language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruit_basket

node_js:
  - 12

before_script:
  - psql -c 'create database fruit_basket;' -U postgres
  - psql -U postgres -d fruit_basket -a -f table.sql

services:
  - postgresql